AWSTemplateFormatVersion: "2010-09-09"
Description: Allow Lambda to send email(s) using SES.
Resources:
  LambdaRoleSESSender:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /LambdaRoles/
      Policies:
                - PolicyName: logs
                  PolicyDocument:
                    Statement:
                        Effect: Allow
                        Action:
                            - "logs:CreateLogGroup"
                            - "logs:CreateLogStream"
                            - "logs:PutLogEvents"
                        Resource: "arn:aws:logs:*:*:*"
                - PolicyName: lambda
                  PolicyDocument:
                    Statement:
                        Effect: Allow
                        Action:
                            - "lambda:InvokeFunction"
                        Resource: "*"
                - PolicyName: sendEmails
                  PolicyDocument:
                    Statement:
                        Effect: Allow
                        Action:
                            - "ses:SendEmail"
                            - "ses:SendRawEmail"
                        Resource: "*"
                - PolicyName: ReadDynamo
                  PolicyDocument:
                    Statement:
                      Effect: Allow
                      Action:
                        - dynamodb:GetItem
                        - dynamodb:Query
                        - dynamodb:Scan
                        - dynamodb:PutItem
                      Resource: arn:aws:dynamodb:us-east-1:838812369035:table/prod_user
                - PolicyName: WorkSQS
                  PolicyDocument:
                    Statement:
                      Effect: Allow
                      Action:
                        - sqs:SendMessage
                        - sqs:DeleteMessage
                        - sqs:ChangeMessageVisibility
                        - sqs:ReceiveMessage
                        - sqs:GetQueueAttributes
                      Resource: arn:aws:sqs:us-east-1:838812369035:ProductionQueueCreateEmail
  LambdaRoleSESSenderInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /InstanceProfiles/
      Roles:
        - !Ref LambdaRoleSESSender
